apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: redis-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: splex7/redis-chat:latest
          ports:
            - containerPort: 8000
