apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: redis-chat
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
